/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HotelDto } from '../../models/hotel-dto';

export interface Hotels$Params {
  name?: string;
  stars?: number;
  city?: number;
  page?: number;
  items?: number;
}

export function hotels(http: HttpClient, rootUrl: string, params?: Hotels$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HotelDto>>> {
  const rb = new RequestBuilder(rootUrl, hotels.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('stars', params.stars, {});
    rb.query('city', params.city, {});
    rb.query('page', params.page, {});
    rb.query('items', params.items, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HotelDto>>;
    })
  );
}

hotels.PATH = '/hotels';
