/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HotelDto } from '../../models/hotel-dto';
import { HotelRequestDto } from '../../models/hotel-request-dto';

export interface UpdateHotel$Params {
  id: number;
      body?: {
'hotel': HotelRequestDto;
'image'?: Blob;
}
}

export function updateHotel(http: HttpClient, rootUrl: string, params: UpdateHotel$Params, context?: HttpContext): Observable<StrictHttpResponse<HotelDto>> {
  const rb = new RequestBuilder(rootUrl, updateHotel.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HotelDto>;
    })
  );
}

updateHotel.PATH = '/hotels/{id}';
