/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HotelDto } from '../../models/hotel-dto';

export interface Upload1$Params {
  id: number;
      body?: {
'image': Blob;
}
}

export function upload1(http: HttpClient, rootUrl: string, params: Upload1$Params, context?: HttpContext): Observable<StrictHttpResponse<HotelDto>> {
  const rb = new RequestBuilder(rootUrl, upload1.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HotelDto>;
    })
  );
}

upload1.PATH = '/hotels/image/{id}';
