/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CityDto } from '../../models/city-dto';

export interface CityDtos$Params {
}

export function cityDtos(http: HttpClient, rootUrl: string, params?: CityDtos$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CityDto>>> {
  const rb = new RequestBuilder(rootUrl, cityDtos.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CityDto>>;
    })
  );
}

cityDtos.PATH = '/cities';
