/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddressDto {
  adresse1: string;
  adresse2?: string;
  codePostale: string;
  pays: string;
  ville: string;
}
