/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressDto } from '../models/address-dto';
export interface ClientResponse {
  active?: boolean;
  address?: AddressDto;
  dateOfBirth?: string;
  email?: string;
  firstname?: string;
  image?: string;
  lastname?: string;
  phoneNumber?: string;
}
