/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CityDto } from '../models/city-dto';
export interface HotelDto {
  address: string;
  city?: CityDto;
  id?: number;
  imageName?: string;
  name: string;
  stars?: number;
}
