/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HotelRequestDto {
  address: string;
  cityId: number;
  name: string;
  stars?: number;
}
