/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressDto } from '../models/address-dto';
export interface RegistrationRequest {
  address: AddressDto;
  confirmPassword: string;
  dateOfBirth: string;
  email: string;
  firstname: string;
  lastname: string;
  password: string;
  phoneNumber: string;
}
