/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientResponse } from '../models/client-response';
import { RoomDto } from '../models/room-dto';
export interface ReservationResponseDto {
  checkInDate?: string;
  checkOutDate?: string;
  client?: ClientResponse;
  id?: number;
  room?: RoomDto;
  state?: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED';
  totalPrice?: number;
}
