/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HotelDto } from '../models/hotel-dto';
import { RoomImageDto } from '../models/room-image-dto';
export interface RoomDto {
  hotelDto?: HotelDto;
  id?: number;
  numberOfRooms?: number;
  price?: number;
  roomImages?: Array<RoomImageDto>;
  surface?: number;
}
