/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReservationResponseDto } from '../../models/reservation-response-dto';

export interface Reservations$Params {
  id: string;
  state?: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED';
  page?: number;
  items?: number;
}

export function reservations(http: HttpClient, rootUrl: string, params: Reservations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReservationResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, reservations.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('state', params.state, {});
    rb.query('page', params.page, {});
    rb.query('items', params.items, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReservationResponseDto>>;
    })
  );
}

reservations.PATH = '/reservations/client/{id}';
