/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoomDto } from '../../models/room-dto';

export interface Available$Params {
  id: number;
  min?: number;
  max?: number;
  rooms?: number;
  checkIn: string;
  checkOut: string;
}

export function available(http: HttpClient, rootUrl: string, params: Available$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoomDto>>> {
  const rb = new RequestBuilder(rootUrl, available.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('min', params.min, {});
    rb.query('max', params.max, {});
    rb.query('rooms', params.rooms, {});
    rb.query('checkIn', params.checkIn, {});
    rb.query('checkOut', params.checkOut, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RoomDto>>;
    })
  );
}

available.PATH = '/rooms/hotel/{id}/available';
