/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoomDto } from '../../models/room-dto';

export interface Rooms$Params {
  hotelId: number;
  min?: number;
  max?: number;
  rooms?: number;
  page?: number;
  items?: number;
}

export function rooms(http: HttpClient, rootUrl: string, params: Rooms$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoomDto>>> {
  const rb = new RequestBuilder(rootUrl, rooms.PATH, 'get');
  if (params) {
    rb.path('hotelId', params.hotelId, {});
    rb.query('min', params.min, {});
    rb.query('max', params.max, {});
    rb.query('rooms', params.rooms, {});
    rb.query('page', params.page, {});
    rb.query('items', params.items, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RoomDto>>;
    })
  );
}

rooms.PATH = '/rooms/hotel/{hotelId}';
