/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AddressDto } from './models/address-dto';
export type { CityDto } from './models/city-dto';
export type { ClientResponse } from './models/client-response';
export type { ExceptionResponse } from './models/exception-response';
export type { HotelDto } from './models/hotel-dto';
export type { HotelRequestDto } from './models/hotel-request-dto';
export type { LoginRequest } from './models/login-request';
export type { LoginResponse } from './models/login-response';
export type { RegistrationRequest } from './models/registration-request';
export type { ReservationRequestDto } from './models/reservation-request-dto';
export type { ReservationResponseDto } from './models/reservation-response-dto';
export type { RoomDto } from './models/room-dto';
export type { RoomImageDto } from './models/room-image-dto';
export type { RoomRequest } from './models/room-request';
