/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { RoomControllerService } from './services/room-controller.service';
export { HotelControllerService } from './services/hotel-controller.service';
export { AuthControllerService } from './services/auth-controller.service';
export { ReservationControllerService } from './services/reservation-controller.service';
export { ClientControllerService } from './services/client-controller.service';
export { CityControllerService } from './services/city-controller.service';
