/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CityDto } from '../models/city-dto';
import { cityDtos } from '../fn/city-controller/city-dtos';
import { CityDtos$Params } from '../fn/city-controller/city-dtos';

@Injectable({ providedIn: 'root' })
export class CityControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `cityDtos()` */
  static readonly CityDtosPath = '/cities';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cityDtos()` instead.
   *
   * This method doesn't expect any request body.
   */
  cityDtos$Response(params?: CityDtos$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CityDto>>> {
    return cityDtos(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cityDtos$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cityDtos(params?: CityDtos$Params, context?: HttpContext): Observable<Array<CityDto>> {
    return this.cityDtos$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CityDto>>): Array<CityDto> => r.body)
    );
  }

}
