/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addFavorite } from '../fn/hotel-controller/add-favorite';
import { AddFavorite$Params } from '../fn/hotel-controller/add-favorite';
import { CityDto } from '../models/city-dto';
import { delete$ } from '../fn/hotel-controller/delete';
import { Delete$Params } from '../fn/hotel-controller/delete';
import { findFavorites } from '../fn/hotel-controller/find-favorites';
import { FindFavorites$Params } from '../fn/hotel-controller/find-favorites';
import { getCities } from '../fn/hotel-controller/get-cities';
import { GetCities$Params } from '../fn/hotel-controller/get-cities';
import { getHotel } from '../fn/hotel-controller/get-hotel';
import { GetHotel$Params } from '../fn/hotel-controller/get-hotel';
import { HotelDto } from '../models/hotel-dto';
import { hotelImage } from '../fn/hotel-controller/hotel-image';
import { HotelImage$Params } from '../fn/hotel-controller/hotel-image';
import { hotels } from '../fn/hotel-controller/hotels';
import { Hotels$Params } from '../fn/hotel-controller/hotels';
import { saveHotel } from '../fn/hotel-controller/save-hotel';
import { SaveHotel$Params } from '../fn/hotel-controller/save-hotel';
import { updateHotel } from '../fn/hotel-controller/update-hotel';
import { UpdateHotel$Params } from '../fn/hotel-controller/update-hotel';
import { upload1 } from '../fn/hotel-controller/upload-1';
import { Upload1$Params } from '../fn/hotel-controller/upload-1';

@Injectable({ providedIn: 'root' })
export class HotelControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getHotel()` */
  static readonly GetHotelPath = '/hotels/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHotel()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHotel$Response(params: GetHotel$Params, context?: HttpContext): Observable<StrictHttpResponse<HotelDto>> {
    return getHotel(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHotel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHotel(params: GetHotel$Params, context?: HttpContext): Observable<HotelDto> {
    return this.getHotel$Response(params, context).pipe(
      map((r: StrictHttpResponse<HotelDto>): HotelDto => r.body)
    );
  }

  /** Path part for operation `updateHotel()` */
  static readonly UpdateHotelPath = '/hotels/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateHotel()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateHotel$Response(params: UpdateHotel$Params, context?: HttpContext): Observable<StrictHttpResponse<HotelDto>> {
    return updateHotel(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateHotel$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateHotel(params: UpdateHotel$Params, context?: HttpContext): Observable<HotelDto> {
    return this.updateHotel$Response(params, context).pipe(
      map((r: StrictHttpResponse<HotelDto>): HotelDto => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/hotels/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return delete$(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<{
}> {
    return this.delete$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `addFavorite()` */
  static readonly AddFavoritePath = '/hotels/like';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addFavorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  addFavorite$Response(params: AddFavorite$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return addFavorite(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addFavorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  addFavorite(params: AddFavorite$Params, context?: HttpContext): Observable<string> {
    return this.addFavorite$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `hotels()` */
  static readonly HotelsPath = '/hotels';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `hotels()` instead.
   *
   * This method doesn't expect any request body.
   */
  hotels$Response(params?: Hotels$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HotelDto>>> {
    return hotels(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `hotels$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  hotels(params?: Hotels$Params, context?: HttpContext): Observable<Array<HotelDto>> {
    return this.hotels$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<HotelDto>>): Array<HotelDto> => r.body)
    );
  }

  /** Path part for operation `saveHotel()` */
  static readonly SaveHotelPath = '/hotels';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveHotel()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveHotel$Response(params?: SaveHotel$Params, context?: HttpContext): Observable<StrictHttpResponse<HotelDto>> {
    return saveHotel(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveHotel$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveHotel(params?: SaveHotel$Params, context?: HttpContext): Observable<HotelDto> {
    return this.saveHotel$Response(params, context).pipe(
      map((r: StrictHttpResponse<HotelDto>): HotelDto => r.body)
    );
  }

  /** Path part for operation `upload1()` */
  static readonly Upload1Path = '/hotels/image/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `upload1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  upload1$Response(params: Upload1$Params, context?: HttpContext): Observable<StrictHttpResponse<HotelDto>> {
    return upload1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `upload1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  upload1(params: Upload1$Params, context?: HttpContext): Observable<HotelDto> {
    return this.upload1$Response(params, context).pipe(
      map((r: StrictHttpResponse<HotelDto>): HotelDto => r.body)
    );
  }

  /** Path part for operation `findFavorites()` */
  static readonly FindFavoritesPath = '/hotels/liked';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findFavorites()` instead.
   *
   * This method doesn't expect any request body.
   */
  findFavorites$Response(params?: FindFavorites$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HotelDto>>> {
    return findFavorites(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findFavorites$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findFavorites(params?: FindFavorites$Params, context?: HttpContext): Observable<Array<HotelDto>> {
    return this.findFavorites$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<HotelDto>>): Array<HotelDto> => r.body)
    );
  }

  /** Path part for operation `hotelImage()` */
  static readonly HotelImagePath = '/hotels/image/{image}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `hotelImage()` instead.
   *
   * This method doesn't expect any request body.
   */
  hotelImage$Response(params: HotelImage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return hotelImage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `hotelImage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  hotelImage(params: HotelImage$Params, context?: HttpContext): Observable<Array<string>> {
    return this.hotelImage$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `getCities()` */
  static readonly GetCitiesPath = '/hotels/cities';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCities()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCities$Response(params?: GetCities$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CityDto>>> {
    return getCities(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCities$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCities(params?: GetCities$Params, context?: HttpContext): Observable<Array<CityDto>> {
    return this.getCities$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CityDto>>): Array<CityDto> => r.body)
    );
  }

}
