/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { cancel } from '../fn/reservation-controller/cancel';
import { Cancel$Params } from '../fn/reservation-controller/cancel';
import { confirm } from '../fn/reservation-controller/confirm';
import { Confirm$Params } from '../fn/reservation-controller/confirm';
import { createReservation } from '../fn/reservation-controller/create-reservation';
import { CreateReservation$Params } from '../fn/reservation-controller/create-reservation';
import { find } from '../fn/reservation-controller/find';
import { Find$Params } from '../fn/reservation-controller/find';
import { ReservationResponseDto } from '../models/reservation-response-dto';
import { reservations } from '../fn/reservation-controller/reservations';
import { Reservations$Params } from '../fn/reservation-controller/reservations';

@Injectable({ providedIn: 'root' })
export class ReservationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createReservation()` */
  static readonly CreateReservationPath = '/reservations';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createReservation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createReservation$Response(params: CreateReservation$Params, context?: HttpContext): Observable<StrictHttpResponse<ReservationResponseDto>> {
    return createReservation(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createReservation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createReservation(params: CreateReservation$Params, context?: HttpContext): Observable<ReservationResponseDto> {
    return this.createReservation$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReservationResponseDto>): ReservationResponseDto => r.body)
    );
  }

  /** Path part for operation `confirm()` */
  static readonly ConfirmPath = '/reservations/confirm/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `confirm()` instead.
   *
   * This method doesn't expect any request body.
   */
  confirm$Response(params: Confirm$Params, context?: HttpContext): Observable<StrictHttpResponse<ReservationResponseDto>> {
    return confirm(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `confirm$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  confirm(params: Confirm$Params, context?: HttpContext): Observable<ReservationResponseDto> {
    return this.confirm$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReservationResponseDto>): ReservationResponseDto => r.body)
    );
  }

  /** Path part for operation `reservations()` */
  static readonly ReservationsPath = '/reservations/client/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reservations()` instead.
   *
   * This method doesn't expect any request body.
   */
  reservations$Response(params: Reservations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReservationResponseDto>>> {
    return reservations(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reservations$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reservations(params: Reservations$Params, context?: HttpContext): Observable<Array<ReservationResponseDto>> {
    return this.reservations$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ReservationResponseDto>>): Array<ReservationResponseDto> => r.body)
    );
  }

  /** Path part for operation `cancel()` */
  static readonly CancelPath = '/reservations/cancel/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cancel()` instead.
   *
   * This method doesn't expect any request body.
   */
  cancel$Response(params: Cancel$Params, context?: HttpContext): Observable<StrictHttpResponse<ReservationResponseDto>> {
    return cancel(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cancel$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cancel(params: Cancel$Params, context?: HttpContext): Observable<ReservationResponseDto> {
    return this.cancel$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReservationResponseDto>): ReservationResponseDto => r.body)
    );
  }

  /** Path part for operation `find()` */
  static readonly FindPath = '/reservations/admin/history';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `find()` instead.
   *
   * This method doesn't expect any request body.
   */
  find$Response(params?: Find$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReservationResponseDto>>> {
    return find(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `find$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  find(params?: Find$Params, context?: HttpContext): Observable<Array<ReservationResponseDto>> {
    return this.find$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ReservationResponseDto>>): Array<ReservationResponseDto> => r.body)
    );
  }

}
