/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { available } from '../fn/room-controller/available';
import { Available$Params } from '../fn/room-controller/available';
import { deleteRoom } from '../fn/room-controller/delete-room';
import { DeleteRoom$Params } from '../fn/room-controller/delete-room';
import { getRoom } from '../fn/room-controller/get-room';
import { GetRoom$Params } from '../fn/room-controller/get-room';
import { RoomDto } from '../models/room-dto';
import { roomImage } from '../fn/room-controller/room-image';
import { RoomImage$Params } from '../fn/room-controller/room-image';
import { rooms } from '../fn/room-controller/rooms';
import { Rooms$Params } from '../fn/room-controller/rooms';
import { save } from '../fn/room-controller/save';
import { Save$Params } from '../fn/room-controller/save';
import { updateRoom } from '../fn/room-controller/update-room';
import { UpdateRoom$Params } from '../fn/room-controller/update-room';

@Injectable({ providedIn: 'root' })
export class RoomControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateRoom()` */
  static readonly UpdateRoomPath = '/rooms/{roomId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateRoom()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateRoom$Response(params: UpdateRoom$Params, context?: HttpContext): Observable<StrictHttpResponse<RoomDto>> {
    return updateRoom(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateRoom$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateRoom(params: UpdateRoom$Params, context?: HttpContext): Observable<RoomDto> {
    return this.updateRoom$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoomDto>): RoomDto => r.body)
    );
  }

  /** Path part for operation `rooms()` */
  static readonly RoomsPath = '/rooms/hotel/{hotelId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rooms()` instead.
   *
   * This method doesn't expect any request body.
   */
  rooms$Response(params: Rooms$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoomDto>>> {
    return rooms(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rooms$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rooms(params: Rooms$Params, context?: HttpContext): Observable<Array<RoomDto>> {
    return this.rooms$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RoomDto>>): Array<RoomDto> => r.body)
    );
  }

  /** Path part for operation `save()` */
  static readonly SavePath = '/rooms/hotel/{hotelId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `save()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  save$Response(params: Save$Params, context?: HttpContext): Observable<StrictHttpResponse<RoomDto>> {
    return save(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `save$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  save(params: Save$Params, context?: HttpContext): Observable<RoomDto> {
    return this.save$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoomDto>): RoomDto => r.body)
    );
  }

  /** Path part for operation `getRoom()` */
  static readonly GetRoomPath = '/rooms/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRoom()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRoom$Response(params: GetRoom$Params, context?: HttpContext): Observable<StrictHttpResponse<RoomDto>> {
    return getRoom(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRoom$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRoom(params: GetRoom$Params, context?: HttpContext): Observable<RoomDto> {
    return this.getRoom$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoomDto>): RoomDto => r.body)
    );
  }

  /** Path part for operation `deleteRoom()` */
  static readonly DeleteRoomPath = '/rooms/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteRoom()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteRoom$Response(params: DeleteRoom$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return deleteRoom(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteRoom$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteRoom(params: DeleteRoom$Params, context?: HttpContext): Observable<{
}> {
    return this.deleteRoom$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `roomImage()` */
  static readonly RoomImagePath = '/rooms/image/{image}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `roomImage()` instead.
   *
   * This method doesn't expect any request body.
   */
  roomImage$Response(params: RoomImage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return roomImage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `roomImage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  roomImage(params: RoomImage$Params, context?: HttpContext): Observable<Array<string>> {
    return this.roomImage$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `available()` */
  static readonly AvailablePath = '/rooms/hotel/{id}/available';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `available()` instead.
   *
   * This method doesn't expect any request body.
   */
  available$Response(params: Available$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoomDto>>> {
    return available(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `available$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  available(params: Available$Params, context?: HttpContext): Observable<Array<RoomDto>> {
    return this.available$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RoomDto>>): Array<RoomDto> => r.body)
    );
  }

}
